# Generated by Django 3.2.3 on 2021-06-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='Image',
        ),
    ]
