# Generated by Django 3.2.3 on 2021-06-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_rename_image_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Image',
            new_name='choose_image',
        ),
    ]
