# Generated by Django 3.2.3 on 2021-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_packagecreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuserupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('E_Mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
