# Generated by Django 3.2.3 on 2021-06-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_auto_20210611_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminuserupdate',
        ),
        migrations.DeleteModel(
            name='alladmin',
        ),
    ]
