# Generated by Django 3.2.3 on 2021-06-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_rename_first_name_allstudents_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Amount',
            new_name='Course_discount',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='Course_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Discount',
            new_name='Course_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Enter_course_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Enter_meta_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Enter_outcome',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Enter_requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Enter_tags',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Free_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Meta_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Provider',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fileToUpload',
        ),
        migrations.RemoveField(
            model_name='course',
            name='from_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview_URL',
        ),
    ]
