# Generated by Django 3.2.3 on 2021-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_auto_20210612_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Enter_Price',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='choose_image',
            new_name='image',
        ),
    ]
