# Generated by Django 3.2.3 on 2021-06-17 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0020_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime'),
        ),
    ]
