# Generated by Django 3.2.3 on 2021-06-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_alter_feedback_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('course_level', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d')),
                ('overview_url', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('free_course', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
